name: Run Sorry Cypress
on:
  push:
    branches:
      - main

jobs:
  sorry-cypress:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn
      - run: yarn run build
      - run: yarn serve -s dist -l 8081
      - run: npx currents run --parallel --record --key WD4QzqyNBXTBHOU6 --ci-build-id cypress-build-init