name: Run Sorry Cypress
on:
  push:
    branches:
      - main

jobs:
  sorry-cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install Currents
      - name: Install currents
        run: yarn add @currents/cli

      # Run all Cypress tests
      - name: Run Cypress on Currents.dev
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn serve
          command: yarn currents run --record --parallel --key ${{ secrets.CURRENTS_RECORD_KEY }} --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}"
